# Generated by Django 5.0.4 on 2024-05-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
