# Generated by Django 5.0.4 on 2024-05-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='temporary_balance',
            field=models.DecimalField(decimal_places=2, default='1000000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='1000000', max_digits=10),
        ),
    ]
