# Generated by Django 5.0.4 on 2024-05-09 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_wallet_temporary_balance_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='temporary_balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='destination_transactions', related_query_name='destination_transaction', to='finance.wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='origin_transactions', related_query_name='origin_transaction', to='finance.wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
