# Generated by Django 5.0.4 on 2024-05-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_transaction_receiver_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(default=12345678, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
