# Generated by Django 5.0.4 on 2024-05-10 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_transaction_amount_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='_amount',
            field=models.BigIntegerField(default=850000019, validators=[django.core.validators.MinValueValidator(1000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='_balance',
            field=models.BigIntegerField(default='1000000', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
